Publish new articule
wolox-training/training-cypress pull request #11
Opened 2020-07-06 23:12 UTC by Erikaguilera123

## Sumary
# I made the automated test to publish the new article and created the method "Login" in the class "Helper"

2020-07-06 23:32 UTC, betoobernal commented on cypress/const/helpers.js
> +  HAVETEXT(IDs.password,VAR.passRegister);
add spaces
```suggestion
  HAVETEXT(IDs.email, VAR.emailRegister);
  HAVETEXT(IDs.password, VAR.passRegister);
```

2020-07-06 23:32 UTC, betoobernal commented on cypress/integration/loginAngular.spec.js
> +    HAVETEXT(IDs.password,VAR.textSmall);
add spaces
```suggestion
    HAVETEXT(IDs.email, VAR.textSmall);
    HAVETEXT(IDs.password, VAR.textSmall);
```

2020-07-06 23:33 UTC, betoobernal commented on cypress/integration/newArticule.spec.js
> +    LOGIN ();
remove space
```suggestion
    LOGIN();
```

2020-07-06 23:33 UTC, betoobernal commented on cypress/integration/newArticule.spec.js
> +      HAVETEXT(IDs.body,VAR.body)
add spaces
```suggestion
      HAVETEXT(IDs.title, VAR.title);
      HAVETEXT(IDs.descripcion, VAR.descripcion);
      HAVETEXT(IDs.body, VAR.body)
```

2020-07-06 23:37 UTC, eledwinn requested changes

2020-07-06 23:37 UTC, eledwinn commented on cypress/const/constants.js
> +  body: "bodybodybodybodybodybodybodybodybody "
Use single quotes whenever possible. Please check if your vscode have tslint installed.

2020-07-06 23:37 UTC, eledwinn commented on cypress/const/helpers.js
>  export function HAVETEXT (elemnt, text) {
Please use cammelCase for function names. Example: `haveText` and `random`

2020-07-06 23:37 UTC, eledwinn commented on cypress/integration/loginAngular.spec.js
> +
Remove empty line

2020-07-06 23:37 UTC, eledwinn commented on cypress/integration/newArticule.spec.js
> +    LOGIN ();
cammelCase here, and no white space between name and parenthesis.

2020-07-06 23:37 UTC, eledwinn commented on cypress/integration/newArticule.spec.js
> +     cy.get(`.${IDs.error}`).contains(VAR.articuleDescripInvalid);
Why not configure the complete selector in the `error` variable?

2020-07-06 23:37 UTC, eledwinn commented on cypress/integration/newArticule.spec.js
> +      HAVETEXT(IDs.body,VAR.body)
cammelCase please, and white spaces after comma 😺

2020-07-06 23:37 UTC, eledwinn commented on cypress/integration/newArticule.spec.js
> +      cy.wait(500);
This wait is really necessary.

2020-07-06 23:37 UTC, eledwinn commented on cypress/page-objects/loginAngular.js
> +
Remove empty line :)

2020-07-06 23:37 UTC, eledwinn commented on cypress/page-objects/newArticule.js
> +
Remove empty line :), and use simple quotes.

2020-07-07 12:49 UTC, Erikaguilera123 commented on cypress/integration/newArticule.spec.js
> +      cy.wait(500);
yes, because  return error the test

2020-07-08 17:59 UTC, eledwinn requested changes

2020-07-08 17:59 UTC, eledwinn commented on cypress/const/constants.js
> +  articuleDescripInvalid: "description can't be blank,is too short (minimum is 1 character)",
Single quotes please

2020-07-08 21:07 UTC, eledwinn approved these changes

2020-07-08 21:09 UTC, Erikaguilera123 commented on cypress/const/constants.js
> +  articuleDescripInvalid: "description can't be blank,is too short (minimum is 1 character)",
double quotes are required

2020-07-08 22:02 UTC, betoobernal commented on cypress/const/constants.js
> +  articuleDescripInvalid: "description can't be blank,is too short (minimum is 1 character)",
escape quotes `\'` of the contractions

2020-07-08 22:02 UTC, betoobernal approved these changes

2020-07-23 16:15 UTC, merged