Practice react
wolox-training/training-cypress pull request #8
Opened 2020-06-19 20:34 UTC by Erikaguilera123

## Sumary

The first training, the scenary og Sing up

2020-06-23 16:43 UTC, betoobernal commented on cypress/const/helpers.js
> +}
indentation.

2020-06-23 16:44 UTC, betoobernal commented on cypress/integration/registroAngular.spec.js
> +
remove space

2020-06-23 16:44 UTC, betoobernal commented on cypress/integration/registroAngular.spec.js
> +
same

2020-06-23 16:45 UTC, betoobernal commented on cypress/integration/registroAngular.spec.js
> +
same

2020-06-23 16:47 UTC, betoobernal commented on cypress/page-objects/registroAngular.js
> +  password: 'input[formcontrolname*="password"',
```suggestion
  name:'input[formcontrolname*="username"]',
  email:'input[formcontrolname*="email"]',
  password: 'input[formcontrolname*="password"]',
```

2020-06-23 16:48 UTC, betoobernal commented on cypress/const/constants.js
> +  nulo:' ',
English*

2020-06-23 16:48 UTC, betoobernal commented on cypress/const/constants.js
> +  pass: 'a1b2c3d4e5',
password*

2020-06-26 14:30 UTC, Erikaguilera123 commented on cypress/integration/registroAngular.spec.js
> +
ok

2020-06-26 14:30 UTC, Erikaguilera123 commented on cypress/integration/registroAngular.spec.js
> +
ok

2020-06-26 14:31 UTC, Erikaguilera123 commented on cypress/integration/registroAngular.spec.js
> +
ok

2020-06-26 14:32 UTC, Erikaguilera123 commented on cypress/page-objects/registroAngular.js
> +  password: 'input[formcontrolname*="password"',
ok

2020-06-26 14:33 UTC, Erikaguilera123 commented on cypress/const/constants.js
> +  pass: 'a1b2c3d4e5',
ok

2020-06-26 14:37 UTC, Erikaguilera123 commented on cypress/const/helpers.js
> +}
ok tab

2020-06-26 19:17 UTC, eledwinn requested changes

2020-06-26 19:17 UTC, eledwinn commented on cypress/integration/registroAngular.spec.js
> +   cy.get(IDs.nameProfile).should('be.visible');
Fix indentation, It should have four spaces

2020-06-26 19:17 UTC, eledwinn commented on cypress/integration/registroAngular.spec.js
> +import { VAR, URL } from '../const/constants';
Use english in file names like `registroAngular.spec.js`.

2020-07-06 23:30 UTC, betoobernal commented on cypress/const/helpers.js
>  }
use a more descriptive name. `RANDOM_NUMBER` for example.

2020-07-23 16:18 UTC, eledwinn approved these changes

2020-07-23 16:19 UTC, Erikaguilera123 commented
this is my master branch of Angular project

2020-07-23 16:19 UTC, closed without merging